# Generated by Django 5.0.4 on 2025-01-16 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'тип транзакции',
                'verbose_name_plural': 'типы транзакций ',
            },
        ),
        migrations.AddField(
            model_name='transactions',
            name='type_transactions',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.typetransactions', verbose_name='тип транзакции'),
        ),
    ]
