# Generated by Django 5.0.4 on 2025-01-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_typetransactions_transactions_type_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typetransactions',
            name='name',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
