# Generated by Django 5.0.4 on 2025-01-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_typetransactions_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
